#!/usr/bin/env python3

"""
This script retrieves data from the FIPAV website and converts it into an iCalendar file (.ics).
The script reads input parameters for the season, series, phase, group, and team from a file.
It then sends a GET request to the FIPAV website to retrieve the data.
The data is in CSV format and is parsed using the pandas library.
Each row of the CSV represents an event, which is then converted into an iCalendar event.
The iCalendar events are added to a calendar and serialized into an iCalendar file.
The resulting iCalendar file is written to stdout.
"""

# Import necessary modules
import argparse # to parse command line arguments
from io import StringIO # to create a file-like object from a string
import pandas as pd  # to work with the data
from datetime import datetime, timedelta # to work with dates and times
import pytz  # to work with timezones
from icalendar import Calendar, Event, vDatetime  # to create an iCalendar file
import requests # to make HTTP requests
import sys # to write to stdout
from urllib.parse import quote # to encode the location as url

# Create an argument parser
parser = argparse.ArgumentParser()
parser.add_argument('input_file', help='Input file containing parameters')
args = parser.parse_args()

# Read input parameters from a file
with open(args.input_file, 'r') as file:
    lines = file.readlines()

def retrieve_fipav_data(stagione, serie, fase, girone, squadra):

    # URL to the FIPAV website
    url = f'https://www.sol.milano.federvolley.it/sol/webRisultati/Calendari.aspx?serie={serie}&fase={fase}&girone={girone}&squadra={squadra}&stagione={stagione}'

    headers = {
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "it-IT,en-US;q=0.9,en;q=0.8",
        "Priority": "u=0, i",
        "Referer": "https://www.sol.milano.federvolley.it/sol/webRisultati/Calendari.aspx",
        "Sec-Ch-Ua": "\"Chromium\";v=\"128\", \"Not;A=Brand\";v=\"24\", \"Google Chrome\";v=\"128\"",
        "Sec-Ch-Ua-Mobile": "?0",
        "Sec-Ch-Ua-Platform": "\"macOS\"",
        "Sec-Fetch-Dest": "document",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-Site": "cross-site",
        "Sec-Fetch-User": "?1",
        "Upgrade-Insecure-Requests": "1",
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
    }

    # GET request to the URL and extract cookies from headers
    response = requests.get(url, headers=headers)
    cookies = response.cookies

    # extract the value of the input field "ctl00$idserie" from the response text
    idserie_start = response.text.find('ctl00_idserie" value="') + len('ctl00$idserie" value="')
    idserie_end = response.text.find('"', idserie_start)
    idserie = response.text[idserie_start:idserie_end]

    # Define the headers and data for the POST request
    headers = {
        'authority': 'www.sol.milano.federvolley.it',
        'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
        'accept-language': 'en-GB,en-US;q=0.9,en;q=0.8',
        'cache-control': 'no-cache',
        'content-type': 'application/x-www-form-urlencoded',
        'cookie': f'ASP.NET_SessionId={cookies["ASP.NET_SessionId"]}; .ASPXANONYMOUS={cookies[".ASPXANONYMOUS"]}',
        'origin': 'https://www.sol.milano.federvolley.it',
        'pragma': 'no-cache',
        'referer': f'{url}',
        'sec-ch-ua': '"Not A(Brand";v="99", "Google Chrome";v="121", "Chromium";v="121"',
        'sec-ch-ua-mobile': '?1',
        'sec-ch-ua-platform': '"Android"',
        'sec-fetch-dest': 'document',
        'sec-fetch-mode': 'navigate',
        'sec-fetch-site': 'same-origin',
        'sec-fetch-user': '?1',
        'upgrade-insecure-requests': '1',
        'user-agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Mobile Safari/537.36',
    }

    data = {
        '__EVENTTARGET' : 'ctl00$contentrisultati$btnStampaSq',
        '__EVENTARGUMENT' : '',
        '__LASTFOCUS' : '',
        'ctl00$iframe' : 'False',
        'ctl00$idfase' : '',
        'ctl00$idserie' : f'{idserie}',
        'ctl00$idgirone' : '',
        'ctl00$idsquadra' : f'{squadra}',
        'ctl00$idstagione' : f'{stagione}',
        'ctl00$tipocamp' : f'{girone}',
        'ctl00$nomenu' : '',
        'ctl00$h' : '240',
        'ctl00$stagione' : f'{stagione}',
        'ctl00$serie' : f'{idserie}',
        'ctl00$girone' : '**',
        'ctl00$squadra' : f'{squadra}',
        'ctl00$contentrisultati$SerieBase' : '',
        'ctl00$contentrisultati$csvmode' : 'on'
    }

    response = requests.post(url, headers=headers, data=data)
    return response.text

def process_fipav_data(input):
    # CSV content is in input
    # strip '=' from the csv file
    input = input.replace('="', '"')
    # Create a StringIO object from the response text
    # This allows us to use the csv module to read the content
    csv_file = StringIO(input)

    # Read the CSV file
    # The file is separated by semicolons
    df = pd.read_csv(csv_file, sep=';')

    # Define the timezone
    timezone = 'Europe/Rome'

    # Create a new calendar
    cal = Calendar()

    # Create a calendar name
    cal.add('prodid', '-//Fabulus-Fipav-ICS//fabioinvernizzi.com//')
    cal.add('version', '2.0')

    # Iterate over the rows of the DataFrame
    # Each row represents an event
    for _, row in df.iterrows():

        # skip row if beginning with 'CAMPIONATO' (header row)
        if row['CAMPIONATO'] == 'CAMPIONATO':
            continue

        # Create an event with a predictable UID
        event = Event()
        # define anno as the year extracted from DATA of the current row
        anno = datetime.strptime(row['DATA'],'%d/%m/%Y').year
        event['uid'] = f"FIPAV-{anno}-{row['CAMPIONATO']}-{row['FASE']}-{row['GIRONE']}-{row['PARTITA']}"

        # Set the event details
        # The details are obtained from the current row of the DataFrame
        event.add('summary', f"[{row['CAMPIONATO']}] {row['OSPITANTE']} vs {row['OSPITE']}")
        event.add('description', f"Campionato:\n{row['DESCAMPIONATO']}\nPartita: {row['PARTITA']}\nGiornata: {row['GIORNATA']}\n")

        location = f"{row['CAMPO']},{row['VIA']}, {row['COMUNE']}"
        map_location = quote(location) # encode the location as url
        event.add('location', location, parameters={'ALTREP':f"https://www.google.com/maps/search/{map_location}"})

        # Combine date and time into a datetime object
        # if can't parse the date, skip the row
        try:
            dt = datetime.strptime(f"{row['DATA']} {row['ORA']}", '%d/%m/%Y %H:%M')
        except ValueError:
            continue

        # Localize the datetime object to the defined timezone
        dt = pytz.timezone(timezone).localize(dt)

        # Set the start and end times of the event
        event.add('dtstart', dt)
        event.add('dtend', dt + timedelta(hours=2))

        # Set the creation/last-update time of the event
        event.add('dtstamp', datetime.now())

        # create a description with the results of the match are not zero
        if row['SETS_OSPITANTE'] != 0 or row['SETS_OSPITE'] != 0:
            event['summary'] += f" [{row['SETS_OSPITANTE']}-{row['SETS_OSPITE']}]"
            event['description'] += f"Risultato: {row['SETS_OSPITANTE']}-{row['SETS_OSPITE']}"
            # force PUNTEGGIO to be a string and remove '=' and '"' characters
            punteggio = str(row['PUNTEGGIO']).replace('=', '').replace('"', '')
            event['description'] += f"\nPunteggio: {punteggio}"


        # add google maps link to the description
        event['description'] += "\n\nhttps://www.google.com/maps/search/" + map_location + "\n"

        # Add the event to the calendar
        cal.add_component(event)

    # Get the iCalendar representation of the calendar
    # The to_ical method returns a bytes that represents the calendar in the iCalendar format
    ics_str = cal.to_ical().decode('utf-8')
    return ics_str

# function to fix missing vtimezone
def add_vtimezone(ics_str):

    vtimezone_data = '''BEGIN:VTIMEZONE
TZID:Europe/Rome
X-LIC-LOCATION:Europe/Rome
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
'''
    vtimezone_data = vtimezone_data.replace('\n','\r\n')
    # insert vtimezone_data in ics_str before the first occurence of 'BEGIN:VEVENT'
    return ics_str.replace('BEGIN:VEVENT', vtimezone_data + 'BEGIN:VEVENT', 1)

# main program

ics_str = ""
input = ""
for line in lines:
    stagione, serie, fase, girone, squadra = line.strip().split()
    input += retrieve_fipav_data(stagione, serie, fase, girone, squadra)

#sys.stdout.write(input)
#exit

ics_str = process_fipav_data(input)
ics_str = add_vtimezone(ics_str)

# write calendar to stdout
sys.stdout.write(ics_str)
